spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-81255a595d6f4e94a25be217b89aa6d3
      chat:
        options:
          model: qwen-plus
search-api:
  api-key: xc-CW4MFzxZw2u1c5yzCNrWjGHARuQootGpj1YuoutTHjYPtkZQ
